name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      destroy_confirm:
        description: 'Type "yes" to confirm destruction'
        required: true
        default: 'no'

jobs:
  terraform:
    name: Destroy Terraform Infrastructure
    runs-on: ubuntu-latest

    env:
      TF_VAR_private_key: ${{ secrets.EC2_PRIVATE_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.3  

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan Destroy
      run: terraform plan -destroy -out=destroy.tfplan

    - name: Terraform Destroy
      if: github.event.inputs.destroy_confirm == 'yes'
      run: terraform apply -auto-approve destroy.tfplan

    - name: Post Destroy Cleanup
      if: always()
      run: rm -rf destroy.tfplan
