name: Terraform

on:
  push:
    branches:
      - master  # or your preferred branch
  pull_request:
    branches:
      - master  # or your preferred branch

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2  # specify your region

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.3  # specify your Terraform version

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=plan.tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve plan.tfplan

    - name: Post Apply Cleanup
      if: always()
      run: rm -rf plan.tfplan
